[package]
name = "scribbles-render"
version = "0.0.1"
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "r"
path = "_rendr/main.rs"
