name: Render and Deploy

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-render-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run - Render
      run: cargo run
    - name: Predeploy - install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PUBLISH_PRIV_KEY }}
        # Generate with: ssh-keyscan -H $HOST
        known_hosts: ${{ secrets.PUBLISH_KNOWN_HOSTS }}
    - name: Deploy with rsync
      run: rsync -avz ./_html.out/ ${{ secrets.PUBLISH_USER }}@${{ secrets.PUBLISH_HOST }}:${{ secrets.PUBLISH_TARGET_DIR }}
